# -*- coding: utf-8 -*-
"""Estrutura de lista-Python_para_Machine_Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWIdEUCxo7MZHIhVRvjzWuSob3nKMJjf

#Criando Estruras em listas

*Como sera que o python sabe que determinado bloco de codigo é uma lisat ?
 Sera que apenas nomeando uma variavel de lista*
"""

lista = 10
type()

"""**Claro que não**!!!

Em python se cria uma lista atribuindo cochetes ao fim de uma variavel
"""

lista = [1 , 2 , 3]
type(lista)

lista2 = [[1,2,3], [4,5,6],[7,8,9]]
type(lista2)

"""Para selecionar um elemento da lista de interesse , deve se passar a colocação daquele elemento no indice da lista """

lista[0]

"""o indice 0 corresponde ao primeiro elemento da nosso primeira lista o elemento 1"""

lista2[0]

"""no caso da lista 2 os elementos são listas com  3 numeros cada , sendo o elemento de indice 0 o elemento [123]

Há mas como eu faço para  selecionar um desses 3 composnentes dessas lisa que forma a lista 2 ? Assim jovem gafalhoto
"""

lista2[2][2]

"""na listaa dois o 2 elemento é [7,8,9]
e o segundo do segundo é o 9

#Funções dentro de listas
"""

import random # função radom
cidade=["são paulo" ,"pernambuco","ceara","sao luis" ]
escolhida = random.choice(cidade)
print("A cidade escolhida é :",escolhida)

"""#Adicionar itens a uma lista

"""

a = [1,2,3]
a.append(5)
print(a)