# -*- coding: utf-8 -*-
"""Transformando tipo de dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RvBgBIwzSONipxfj63WkAIkXHdtTSLcz

#Transformando tipo de dados (int , float)

- ** Transformando elementos de uma lista e inteiros para float **
"""

lista = [2 ,4 ,10 ,6]
type(lista)

nova_lista = []
for i in lista:
  nova_lista.append(float(i))
print(nova_lista)